apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: the-project-staging
resources:
- ../../base
- namespace.yaml
images:
- name: eetujukka/devops-with-kubernetes-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-backend
  newTag: 2e60f40e87e99f3cb27e523a897a6eabcf04a1c3
- name: eetujukka/devops-with-kubernetes-frontend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-frontend
  newTag: 2e60f40e87e99f3cb27e523a897a6eabcf04a1c3
