apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: the-project-staging
resources:
- ../../base
- namespace.yaml
images:
- name: eetujukka/devops-with-kubernetes-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-backend
  newTag: a50648e71f212b5170fff38e4738071186cc1bef
- name: eetujukka/devops-with-kubernetes-frontend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-frontend
  newTag: a50648e71f212b5170fff38e4738071186cc1bef
