apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: the-project-staging
resources:
- ../../base
- namespace.yaml
images:
- name: eetujukka/devops-with-kubernetes-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-backend
  newTag: 61cbf176b80349c2cfe3120e722deda51be77a66
- name: eetujukka/devops-with-kubernetes-frontend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-frontend
  newTag: 61cbf176b80349c2cfe3120e722deda51be77a66
