apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: the-project-prod
resources:
- ../../base
- namespace.yaml
- jobs/pg-dump.yaml
patches:
- path: broadcaster-slack-webhook-patch.yaml
images:
- name: eetujukka/devops-with-kubernetes-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-backend
  newTag: 4e73e7ef5a0ed939ae85399afa553a277c4f59e1
- name: eetujukka/devops-with-kubernetes-frontend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-frontend
  newTag: 4e73e7ef5a0ed939ae85399afa553a277c4f59e1
