apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: the-project-prod
resources:
- ../../base
- namespace.yaml
- jobs/pg-dump.yaml
patches:
- path: broadcaster-slack-webhook-patch.yaml
images:
- name: eetujukka/devops-with-kubernetes-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-backend
  newTag: 74c844c932e13ed9c91f8f2d8d8a1219db96633e
- name: eetujukka/devops-with-kubernetes-frontend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-frontend
  newTag: 74c844c932e13ed9c91f8f2d8d8a1219db96633e
