apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: the-project-prod
resources:
- ../../base
- namespace.yaml
- jobs/pg-dump.yaml
patches:
- path: broadcaster-slack-webhook-patch.yaml
images:
- name: eetujukka/devops-with-kubernetes-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-backend
  newTag: d47d7d339520a763a4cd9407781f671ec5d1e12e
- name: eetujukka/devops-with-kubernetes-frontend
  newName: europe-north1-docker.pkg.dev/dwk-gke-504310/devops-with-kubernetes/devops-with-kubernetes-frontend
  newTag: d47d7d339520a763a4cd9407781f671ec5d1e12e
