apiVersion: v1
kind: Secret
metadata:
    name: project-postgres-password
    namespace: the-project-prod
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1i99yTFxoyV4dG/6,iv:cPvfNfMMnTyfDTxGi/7uspJIsNYnw9t0na1Qj+f9LJ0=,tag:qSff7AXQDJU/ApqLapKD3A==,type:str]
stringData:
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:dS8x1420sNcxtvI/k+q0TZpoBPJjTRI0cstEsPKfLWI5W4NxS/oXflfW/gQJr4OvH3wDVfl6KdppKYLWXgD+qU6ZImBI8/0cqC3nOorNiSLC,iv:tDwKHXicw3jLug6giVxapDSYaIocxEtxIG0NSZFpqsY=,tag:vL8f1aHNARMopEdTxMyuTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRTV0dTdROCtCRHZiSUpB
            NWFHNkJUTE9TY3BjWUdudmtTSy9tVW5BdG5JCmMwUU5aT3BsajhJai9NSnNFQlBo
            WkREUXQ4ZWNOL2k2QXdOMS9OYUlyMU0KLS0tIDZuY2dCMVFVYU9MMjZFYktaaHNp
            ME5CMG1LQzVCdFo2bGRCb1FGMmFYL1UKifHhuDNFiI/sv51H0O8Nkn9p6WHmPt+K
            A2QpuyAdAzw+YPQS0uJcc/P01MinlAKYCAsybW8/R1iLgk7AMm5xZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mgq9ygh23q0cr00mjn0dfn8msak0apdy0ymjv5k50qzy75zmfkqzjdam4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T14:01:19Z"
    mac: ENC[AES256_GCM,data:DCb38jKiIXGyPTvgB5Aq/r3h5E0PY9x8tLogCz58hHP9GB2UtiHwJoFnkRL0QdmfYUqe3BwAHH2E7TeF/3O/Nplq9MLH/wKcIlbb/DoxaPPRMTm6Dip5hy8wFMucXL22OAX8+gwk4kD+KXy6aU0THqk7a5MXPblJkWXUtssxhH0=,iv:I73AxLxkESDo3yDNDMSO1mO8yjkigfmHJt6KFX0wTOM=,tag:Z+cAJN5Z1TRU3A6iljlzxQ==,type:str]
    version: 3.13.2
