apiVersion: v1
kind: ConfigMap
metadata:
  name: the-project-config-map
data:
  backend.port: "3001"
  frontend.port: "3000"
  frontend.apiBaseUrl: "/api"
  loki.url: "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
  loki.tenantId: "1"
  nats.url: "nats://my-nats.nats.svc.cluster.local:4222"
  nats.todoCreatedSubject: "todos.created"
  nats.queueGroup: "todo-broadcasters"
  broadcaster.logFilePath: "/tmp/broadcaster/todo-events.log"
  picsum.url: "https://picsum.photos/seed/${seed}/1200/640"
  postgres.database: "project"
  postgres.user: "project"
