apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: the-project-v2-claim
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
