apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikibot
spec:
  schedule: "* 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wikibot
              image: eetujukka/devops-with-kubernetes-wikibot:1.0
              imagePullPolicy: IfNotPresent
              env:
                - name: BACKEND_URL
                  value: "http://devops-with-kubernetes-backend-svc:3001"
          restartPolicy: OnFailure
